/**
 * C.A.A.S. — Sistema de Traducciones
 * Idiomas: ES, EN, ZH (Chino), JA (Japonés), PT (Portugués Brasil)
 */
const CAAS_LANG = {

  // ── ESPAÑOL (default) ──────────────────────────────────────────
  es: {
    // Navbar
    nav_home:        'Inicio',
    nav_login:       'Iniciar Sesión',
    nav_register:    'Registrarse',
    nav_panel:       'Mi Panel',
    nav_admin:       'Admin',
    nav_logout:      'Salir',
    nav_settings:    'Ajustes',
    nav_hello:       'Hola',

    // Index
    hero_title:      'Encontrá tu comida favorita',
    hero_sub:        'Los mejores locales del barrio, en un solo lugar.',
    search_ph:       'Buscar local o plato...',
    search_cats:     'Todas las categorías',
    search_btn:      'Buscar',
    found_singular:  'local encontrado',
    found_plural:    'locales encontrados',
    no_results:      'No se encontraron locales.',
    see_all:         'Ver todos',
    no_dishes:       'Este local aún no publicó platos.',
    see_local:       'Ver local →',

    // Modal pedido
    modal_notes_ph:  'Aclaraciones (sin cebolla, extra queso...)',
    modal_cancel:    'Cancelar',
    modal_confirm:   'Confirmar',
    modal_sending:   'Enviando...',
    modal_login_warn:'Iniciá sesión como cliente para pedir.',
    modal_success:   '¡Pedido registrado!',
    modal_conn_err:  'Error de conexión.',

    // Login
    login_title:     'Bienvenido de vuelta',
    login_sub:       'Ingresá con tu email o teléfono',
    login_input_ph:  'Email o Teléfono',
    login_pass_ph:   'Contraseña',
    login_btn:       'Entrar',
    login_no_acc:    '¿No tenés cuenta?',
    login_register:  'Registrarse',
    login_demo:      'Sistema en modo demostración.',
    login_success:   '¡Registro exitoso! Ya podés ingresar.',

    // Registro
    reg_title:       'Crear una Cuenta',
    reg_type_lbl:    'Tipo de cuenta *',
    reg_type_ph:     '— Seleccioná —',
    reg_client:      'Cliente',
    reg_company:     'Empresa / Local',
    reg_name_ph:     'Nombre completo / Nombre del local *',
    reg_email_ph:    'Email *',
    reg_tel_ph:      'Teléfono / WhatsApp *',
    reg_pass_ph:     'Contraseña (mín. 8 caracteres) *',
    reg_pending:     'Las empresas quedan en estado Pendiente hasta ser aprobadas.',
    reg_delivery:    'Dirección de entrega',
    reg_street_ph:   'Calle',
    reg_house_ph:    'Número de casa / Apto',
    reg_biz_data:    'Datos del local',
    reg_cat_ph:      'Categoría (ej: Hamburguesería, Pizzería) *',
    reg_hours_ph:    'Horarios (ej: 19:00 - 00:00)',
    reg_addr_ph:     'Dirección del local',
    reg_btn:         'Registrarse',
    reg_have_acc:    '¿Ya tenés cuenta?',
    reg_login:       'Iniciar Sesión',

    // Local
    local_back:      '← Volver',
    local_address:   'Dirección',
    local_hours:     'Horarios',
    local_menu:      'Menú',
    local_no_dishes: 'Este local aún no publicó platos.',
    local_order:     'Pedir',
    local_confirm:   '✓ Confirmar',
    local_notes_ph:  'Aclaraciones opcionales...',

    // Empresa panel
    emp_orders:      'Pedidos Recibidos',
    emp_live:        'En Vivo',
    emp_no_orders:   'No hay pedidos aún.',
    emp_add_dish:    'Agregar Plato',
    emp_dish_name:   'Nombre del plato *',
    emp_dish_price:  'Precio ($) *',
    emp_dish_desc:   'Descripción...',
    emp_dish_img:    'Imagen (jpg/png/webp, máx 3MB)',
    emp_publish:     'Publicar Plato',
    emp_published:   'Platos Publicados',
    emp_delete:      'Eliminar',
    emp_no_dishes:   'Aún no publicaste ningún plato.',

    // Admin panel
    adm_pending:     'Empresas Pendientes de Verificación',
    adm_approve:     '✓ Aprobar',
    adm_reject:      '✕ Rechazar',
    adm_companies:   'Empresas Registradas',
    adm_total:       'total',
    adm_orders:      'Control de Pedidos Globales',
    adm_search_ph:   'Buscar por cliente, empresa, estado...',
    adm_search_btn:  'Buscar',
    adm_clear:       'Limpiar',
    adm_no_results:  'Sin resultados.',
    adm_loading:     'Cargando...',

    // Estados pedido
    st_pending:      'Pendiente',
    st_preparing:    'En preparación',
    st_onway:        'En camino',
    st_delivered:    'Entregado',
    st_cancelled:    'Cancelado',

    // Ajustes
    settings_title:  'Ajustes',
    settings_theme:  'Apariencia',
    settings_light:  'Modo Claro',
    settings_dark:   'Modo Oscuro',
    settings_lang:   'Idioma',
    settings_save:   '¡Preferencias guardadas!',
    settings_back:   'Volver al inicio',
  },

  // ── ENGLISH ────────────────────────────────────────────────────
  en: {
    nav_home:        'Home',
    nav_login:       'Sign In',
    nav_register:    'Sign Up',
    nav_panel:       'My Panel',
    nav_admin:       'Admin',
    nav_logout:      'Sign Out',
    nav_settings:    'Settings',
    nav_hello:       'Hello',

    hero_title:      'Find your favorite food',
    hero_sub:        'The best local restaurants, all in one place.',
    search_ph:       'Search restaurant or dish...',
    search_cats:     'All categories',
    search_btn:      'Search',
    found_singular:  'restaurant found',
    found_plural:    'restaurants found',
    no_results:      'No restaurants found.',
    see_all:         'See all',
    no_dishes:       'This restaurant has no dishes yet.',
    see_local:       'View restaurant →',

    modal_notes_ph:  'Notes (no onion, extra cheese...)',
    modal_cancel:    'Cancel',
    modal_confirm:   'Confirm',
    modal_sending:   'Sending...',
    modal_login_warn:'Sign in as a customer to order.',
    modal_success:   'Order placed!',
    modal_conn_err:  'Connection error.',

    login_title:     'Welcome back',
    login_sub:       'Sign in with your email or phone',
    login_input_ph:  'Email or Phone',
    login_pass_ph:   'Password',
    login_btn:       'Sign In',
    login_no_acc:    "Don't have an account?",
    login_register:  'Sign Up',
    login_demo:      'System in demo mode.',
    login_success:   'Registration successful! You can now sign in.',

    reg_title:       'Create an Account',
    reg_type_lbl:    'Account type *',
    reg_type_ph:     '— Select —',
    reg_client:      'Customer',
    reg_company:     'Business / Restaurant',
    reg_name_ph:     'Full name / Business name *',
    reg_email_ph:    'Email *',
    reg_tel_ph:      'Phone / WhatsApp *',
    reg_pass_ph:     'Password (min. 8 characters) *',
    reg_pending:     'Businesses remain Pending until approved by the administrator.',
    reg_delivery:    'Delivery address',
    reg_street_ph:   'Street',
    reg_house_ph:    'House number / Apt',
    reg_biz_data:    'Business details',
    reg_cat_ph:      'Category (e.g.: Burger, Pizza) *',
    reg_hours_ph:    'Hours (e.g.: 7pm - 12am)',
    reg_addr_ph:     'Business address',
    reg_btn:         'Sign Up',
    reg_have_acc:    'Already have an account?',
    reg_login:       'Sign In',

    local_back:      '← Back',
    local_address:   'Address',
    local_hours:     'Hours',
    local_menu:      'Menu',
    local_no_dishes: 'No dishes available yet.',
    local_order:     'Order',
    local_confirm:   '✓ Confirm',
    local_notes_ph:  'Optional notes...',

    emp_orders:      'Received Orders',
    emp_live:        'Live',
    emp_no_orders:   'No orders yet.',
    emp_add_dish:    'Add Dish',
    emp_dish_name:   'Dish name *',
    emp_dish_price:  'Price ($) *',
    emp_dish_desc:   'Description...',
    emp_dish_img:    'Image (jpg/png/webp, max 3MB)',
    emp_publish:     'Publish Dish',
    emp_published:   'Published Dishes',
    emp_delete:      'Delete',
    emp_no_dishes:   'No dishes published yet.',

    adm_pending:     'Businesses Pending Verification',
    adm_approve:     '✓ Approve',
    adm_reject:      '✕ Reject',
    adm_companies:   'Registered Businesses',
    adm_total:       'total',
    adm_orders:      'Global Order Control',
    adm_search_ph:   'Search by customer, business, status...',
    adm_search_btn:  'Search',
    adm_clear:       'Clear',
    adm_no_results:  'No results.',
    adm_loading:     'Loading...',

    st_pending:      'Pending',
    st_preparing:    'Preparing',
    st_onway:        'On the way',
    st_delivered:    'Delivered',
    st_cancelled:    'Cancelled',

    settings_title:  'Settings',
    settings_theme:  'Appearance',
    settings_light:  'Light Mode',
    settings_dark:   'Dark Mode',
    settings_lang:   'Language',
    settings_save:   'Preferences saved!',
    settings_back:   'Back to home',
  },

  // ── 中文 (Chino Simplificado) ──────────────────────────────────
  zh: {
    nav_home:        '首页',
    nav_login:       '登录',
    nav_register:    '注册',
    nav_panel:       '我的面板',
    nav_admin:       '管理',
    nav_logout:      '退出',
    nav_settings:    '设置',
    nav_hello:       '你好',

    hero_title:      '找到你最喜欢的食物',
    hero_sub:        '附近最好的餐厅，尽在一处。',
    search_ph:       '搜索餐厅或菜肴...',
    search_cats:     '所有分类',
    search_btn:      '搜索',
    found_singular:  '家餐厅',
    found_plural:    '家餐厅',
    no_results:      '未找到餐厅。',
    see_all:         '查看全部',
    no_dishes:       '该餐厅暂无菜肴。',
    see_local:       '查看餐厅 →',

    modal_notes_ph:  '备注（不要洋葱，加奶酪...）',
    modal_cancel:    '取消',
    modal_confirm:   '确认',
    modal_sending:   '发送中...',
    modal_login_warn:'请以顾客身份登录后下单。',
    modal_success:   '订单已提交！',
    modal_conn_err:  '连接错误。',

    login_title:     '欢迎回来',
    login_sub:       '用邮箱或电话登录',
    login_input_ph:  '邮箱或电话',
    login_pass_ph:   '密码',
    login_btn:       '登录',
    login_no_acc:    '还没有账号？',
    login_register:  '注册',
    login_demo:      '系统演示模式。',
    login_success:   '注册成功！您现在可以登录。',

    reg_title:       '创建账号',
    reg_type_lbl:    '账号类型 *',
    reg_type_ph:     '— 请选择 —',
    reg_client:      '顾客',
    reg_company:     '商家 / 餐厅',
    reg_name_ph:     '全名 / 商家名称 *',
    reg_email_ph:    '邮箱 *',
    reg_tel_ph:      '电话 / WhatsApp *',
    reg_pass_ph:     '密码（至少8位）*',
    reg_pending:     '商家注册后需等待管理员审核。',
    reg_delivery:    '收货地址',
    reg_street_ph:   '街道',
    reg_house_ph:    '门牌号',
    reg_biz_data:    '商家信息',
    reg_cat_ph:      '分类（如：汉堡，披萨）*',
    reg_hours_ph:    '营业时间（如：19:00 - 00:00）',
    reg_addr_ph:     '商家地址',
    reg_btn:         '注册',
    reg_have_acc:    '已有账号？',
    reg_login:       '登录',

    local_back:      '← 返回',
    local_address:   '地址',
    local_hours:     '营业时间',
    local_menu:      '菜单',
    local_no_dishes: '暂无菜肴。',
    local_order:     '下单',
    local_confirm:   '✓ 确认',
    local_notes_ph:  '可选备注...',

    emp_orders:      '收到的订单',
    emp_live:        '实时',
    emp_no_orders:   '暂无订单。',
    emp_add_dish:    '添加菜肴',
    emp_dish_name:   '菜肴名称 *',
    emp_dish_price:  '价格（$）*',
    emp_dish_desc:   '描述...',
    emp_dish_img:    '图片（jpg/png/webp，最大3MB）',
    emp_publish:     '发布菜肴',
    emp_published:   '已发布菜肴',
    emp_delete:      '删除',
    emp_no_dishes:   '尚未发布任何菜肴。',

    adm_pending:     '待审核商家',
    adm_approve:     '✓ 批准',
    adm_reject:      '✕ 拒绝',
    adm_companies:   '已注册商家',
    adm_total:       '总计',
    adm_orders:      '全局订单管理',
    adm_search_ph:   '按顾客、商家、状态搜索...',
    adm_search_btn:  '搜索',
    adm_clear:       '清除',
    adm_no_results:  '无结果。',
    adm_loading:     '加载中...',

    st_pending:      '待处理',
    st_preparing:    '准备中',
    st_onway:        '配送中',
    st_delivered:    '已送达',
    st_cancelled:    '已取消',

    settings_title:  '设置',
    settings_theme:  '外观',
    settings_light:  '浅色模式',
    settings_dark:   '深色模式',
    settings_lang:   '语言',
    settings_save:   '偏好设置已保存！',
    settings_back:   '返回首页',
  },

  // ── 日本語 (Japonés) ───────────────────────────────────────────
  ja: {
    nav_home:        'ホーム',
    nav_login:       'ログイン',
    nav_register:    '登録',
    nav_panel:       'マイパネル',
    nav_admin:       '管理',
    nav_logout:      'ログアウト',
    nav_settings:    '設定',
    nav_hello:       'こんにちは',

    hero_title:      'お気に入りの料理を見つけよう',
    hero_sub:        '近所の最高のレストランが一か所に。',
    search_ph:       'レストランや料理を検索...',
    search_cats:     'すべてのカテゴリ',
    search_btn:      '検索',
    found_singular:  '件のレストラン',
    found_plural:    '件のレストラン',
    no_results:      'レストランが見つかりません。',
    see_all:         'すべて見る',
    no_dishes:       'このレストランにはまだ料理がありません。',
    see_local:       'レストランを見る →',

    modal_notes_ph:  '備考（玉ねぎなし、チーズ追加...）',
    modal_cancel:    'キャンセル',
    modal_confirm:   '確認',
    modal_sending:   '送信中...',
    modal_login_warn:'注文するには顧客としてログインしてください。',
    modal_success:   '注文が完了しました！',
    modal_conn_err:  '接続エラー。',

    login_title:     'おかえりなさい',
    login_sub:       'メールまたは電話番号でログイン',
    login_input_ph:  'メールまたは電話番号',
    login_pass_ph:   'パスワード',
    login_btn:       'ログイン',
    login_no_acc:    'アカウントをお持ちでない方は',
    login_register:  '登録',
    login_demo:      'デモモード中。',
    login_success:   '登録完了！ログインできます。',

    reg_title:       'アカウント作成',
    reg_type_lbl:    'アカウントの種類 *',
    reg_type_ph:     '— 選択してください —',
    reg_client:      '顧客',
    reg_company:     '企業 / レストラン',
    reg_name_ph:     '氏名 / 店舗名 *',
    reg_email_ph:    'メール *',
    reg_tel_ph:      '電話 / WhatsApp *',
    reg_pass_ph:     'パスワード（8文字以上）*',
    reg_pending:     '企業は管理者の承認後に利用可能になります。',
    reg_delivery:    '配達先住所',
    reg_street_ph:   '通り',
    reg_house_ph:    '番地 / 部屋番号',
    reg_biz_data:    '店舗情報',
    reg_cat_ph:      'カテゴリ（例：バーガー、ピザ）*',
    reg_hours_ph:    '営業時間（例：19:00 - 00:00）',
    reg_addr_ph:     '店舗住所',
    reg_btn:         '登録する',
    reg_have_acc:    'すでにアカウントをお持ちの方は',
    reg_login:       'ログイン',

    local_back:      '← 戻る',
    local_address:   '住所',
    local_hours:     '営業時間',
    local_menu:      'メニュー',
    local_no_dishes: 'まだ料理がありません。',
    local_order:     '注文する',
    local_confirm:   '✓ 確認',
    local_notes_ph:  '任意のメモ...',

    emp_orders:      '受注一覧',
    emp_live:        'ライブ',
    emp_no_orders:   'まだ注文はありません。',
    emp_add_dish:    '料理を追加',
    emp_dish_name:   '料理名 *',
    emp_dish_price:  '価格（$）*',
    emp_dish_desc:   '説明...',
    emp_dish_img:    '画像（jpg/png/webp、最大3MB）',
    emp_publish:     '料理を公開',
    emp_published:   '公開済みの料理',
    emp_delete:      '削除',
    emp_no_dishes:   'まだ料理を公開していません。',

    adm_pending:     '承認待ちの企業',
    adm_approve:     '✓ 承認',
    adm_reject:      '✕ 拒否',
    adm_companies:   '登録済み企業',
    adm_total:       '合計',
    adm_orders:      '注文全体管理',
    adm_search_ph:   '顧客、企業、ステータスで検索...',
    adm_search_btn:  '検索',
    adm_clear:       'クリア',
    adm_no_results:  '結果なし。',
    adm_loading:     '読み込み中...',

    st_pending:      '保留中',
    st_preparing:    '準備中',
    st_onway:        '配達中',
    st_delivered:    '配達完了',
    st_cancelled:    'キャンセル',

    settings_title:  '設定',
    settings_theme:  '外観',
    settings_light:  'ライトモード',
    settings_dark:   'ダークモード',
    settings_lang:   '言語',
    settings_save:   '設定が保存されました！',
    settings_back:   'ホームに戻る',
  },

  // ── PORTUGUÊS BRASIL ───────────────────────────────────────────
  pt: {
    nav_home:        'Início',
    nav_login:       'Entrar',
    nav_register:    'Cadastrar',
    nav_panel:       'Meu Painel',
    nav_admin:       'Admin',
    nav_logout:      'Sair',
    nav_settings:    'Configurações',
    nav_hello:       'Olá',

    hero_title:      'Encontre sua comida favorita',
    hero_sub:        'Os melhores restaurantes do bairro, em um só lugar.',
    search_ph:       'Buscar restaurante ou prato...',
    search_cats:     'Todas as categorias',
    search_btn:      'Buscar',
    found_singular:  'restaurante encontrado',
    found_plural:    'restaurantes encontrados',
    no_results:      'Nenhum restaurante encontrado.',
    see_all:         'Ver todos',
    no_dishes:       'Este restaurante ainda não publicou pratos.',
    see_local:       'Ver restaurante →',

    modal_notes_ph:  'Observações (sem cebola, queijo extra...)',
    modal_cancel:    'Cancelar',
    modal_confirm:   'Confirmar',
    modal_sending:   'Enviando...',
    modal_login_warn:'Faça login como cliente para pedir.',
    modal_success:   'Pedido registrado!',
    modal_conn_err:  'Erro de conexão.',

    login_title:     'Bem-vindo de volta',
    login_sub:       'Entre com seu e-mail ou telefone',
    login_input_ph:  'E-mail ou Telefone',
    login_pass_ph:   'Senha',
    login_btn:       'Entrar',
    login_no_acc:    'Não tem conta?',
    login_register:  'Cadastrar',
    login_demo:      'Sistema em modo demonstração.',
    login_success:   'Cadastro realizado! Você já pode entrar.',

    reg_title:       'Criar uma Conta',
    reg_type_lbl:    'Tipo de conta *',
    reg_type_ph:     '— Selecione —',
    reg_client:      'Cliente',
    reg_company:     'Empresa / Restaurante',
    reg_name_ph:     'Nome completo / Nome do restaurante *',
    reg_email_ph:    'E-mail *',
    reg_tel_ph:      'Telefone / WhatsApp *',
    reg_pass_ph:     'Senha (mín. 8 caracteres) *',
    reg_pending:     'Empresas ficam Pendentes até serem aprovadas pelo administrador.',
    reg_delivery:    'Endereço de entrega',
    reg_street_ph:   'Rua',
    reg_house_ph:    'Número / Apartamento',
    reg_biz_data:    'Dados do restaurante',
    reg_cat_ph:      'Categoria (ex: Hamburgueria, Pizzaria) *',
    reg_hours_ph:    'Horários (ex: 19h - 00h)',
    reg_addr_ph:     'Endereço do restaurante',
    reg_btn:         'Cadastrar',
    reg_have_acc:    'Já tem uma conta?',
    reg_login:       'Entrar',

    local_back:      '← Voltar',
    local_address:   'Endereço',
    local_hours:     'Horários',
    local_menu:      'Cardápio',
    local_no_dishes: 'Nenhum prato disponível ainda.',
    local_order:     'Pedir',
    local_confirm:   '✓ Confirmar',
    local_notes_ph:  'Observações opcionais...',

    emp_orders:      'Pedidos Recebidos',
    emp_live:        'Ao Vivo',
    emp_no_orders:   'Nenhum pedido ainda.',
    emp_add_dish:    'Adicionar Prato',
    emp_dish_name:   'Nome do prato *',
    emp_dish_price:  'Preço (R$) *',
    emp_dish_desc:   'Descrição...',
    emp_dish_img:    'Imagem (jpg/png/webp, máx 3MB)',
    emp_publish:     'Publicar Prato',
    emp_published:   'Pratos Publicados',
    emp_delete:      'Excluir',
    emp_no_dishes:   'Nenhum prato publicado ainda.',

    adm_pending:     'Empresas Pendentes de Verificação',
    adm_approve:     '✓ Aprovar',
    adm_reject:      '✕ Rejeitar',
    adm_companies:   'Empresas Cadastradas',
    adm_total:       'total',
    adm_orders:      'Controle Global de Pedidos',
    adm_search_ph:   'Buscar por cliente, empresa, status...',
    adm_search_btn:  'Buscar',
    adm_clear:       'Limpar',
    adm_no_results:  'Sem resultados.',
    adm_loading:     'Carregando...',

    st_pending:      'Pendente',
    st_preparing:    'Em preparo',
    st_onway:        'A caminho',
    st_delivered:    'Entregue',
    st_cancelled:    'Cancelado',

    settings_title:  'Configurações',
    settings_theme:  'Aparência',
    settings_light:  'Modo Claro',
    settings_dark:   'Modo Escuro',
    settings_lang:   'Idioma',
    settings_save:   'Preferências salvas!',
    settings_back:   'Voltar ao início',
  },
};
